default:
  outputs:
    dev:
      type: synapse
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: "{{ env_var('SYNAPSE_DB_SERVER') }}" # (Dedicated SQL endpoint of your workspace here)
      port: "{{ env_var('SYNAPSE_DB_PORT') | int }}"
      database: "{{ env_var('SYNAPSE_DB_NAME') }}"
      schema: "{{ env_var('SYNAPSE_DB_SCHEMA') }}"
      user: "{{ env_var('SYNAPSE_DB_USER') }}"
      password: "{{ env_var('SYNAPSE_DB_PASSWORD') }}"
  target: dev