with source_data as (
    select 
    ID as PATIENT_ID,
    BIRTHDATE as PATIENT_BIRTH_DATE,
    DEATHDATE as PATIENT_DEATH_DATE,
    PREFIX as PATIENT_PREFIX,
    FIRST as PATIENT_FIRST,
    LAST as PATIENT_LAST,
    MARITAL as PATIENT_MARITAL,
    GENDER as PATIENT_GENDER,
    BIRTHPLACE as PATIENT_BIRTH_PLACE,
    ETHNICITY as PATIENT_ETHNICITY,
    ' ' as PATIENT_RELIGION,
    SSN as PATIENT_NHS_NUMBER,
    ' ' as PATIENT_COMMUNICATION_METHOD,
    ADDRESS as PATIENT_ADDRESS,
    CITY as PATIENT_CITY,
    ZIP as PATIENT_POST_CODE,
    INCOME as PATIENT_PHONE_NUMBER,
    ' ' as PATIENT_EMAIL_ADDRESS,
    ' ' as PATIENT_CONTACT_PREFERNECE,
    ' ' as PATIENT_LSOA
    from {{ ref('patients')}} as p
)

select *
from source_data
